/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Jose
 */
public class ClimedMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form ClimedMDIApplication
     */
    public ClimedMDIApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneMdi = new javax.swing.JSplitPane();
        desktopPaneMdi = new javax.swing.JDesktopPane();
        financeiroMenu = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        agendaMenu = new javax.swing.JMenu();
        agendamentoMenuItem = new javax.swing.JMenuItem();
        horarioMedicoMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        CadastroMenu = new javax.swing.JMenu();
        pacienteMenuItem = new javax.swing.JMenuItem();
        medicoMenuItem = new javax.swing.JMenuItem();
        convenioMenuItem = new javax.swing.JMenuItem();
        especialidadeMenuItem = new javax.swing.JMenuItem();
        estoqueMenuItem = new javax.swing.JMenuItem();
        cadastroSeparator = new javax.swing.JPopupMenu.Separator();
        calendarioMenuItem = new javax.swing.JMenuItem();
        consultaCidMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        grpfinanceiraMenuItem = new javax.swing.JMenuItem();
        despesaMenuItem = new javax.swing.JMenuItem();
        grmdespesaMenuItem = new javax.swing.JMenuItem();
        ctapagarMenuItem = new javax.swing.JMenuItem();
        relatorioMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPaneMdi.setResizeWeight(0.1);
        jSplitPaneMdi.setOneTouchExpandable(true);
        jSplitPaneMdi.setPreferredSize(new java.awt.Dimension(107, 403));
        jSplitPaneMdi.setRightComponent(desktopPaneMdi);

        javax.swing.GroupLayout financeiroMenuLayout = new javax.swing.GroupLayout(financeiroMenu);
        financeiroMenu.setLayout(financeiroMenuLayout);
        financeiroMenuLayout.setHorizontalGroup(
            financeiroMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        financeiroMenuLayout.setVerticalGroup(
            financeiroMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jSplitPaneMdi.setLeftComponent(financeiroMenu);

        agendaMenu.setMnemonic('f');
        agendaMenu.setText("Agenda");

        agendamentoMenuItem.setMnemonic('o');
        agendamentoMenuItem.setText("Agendamento");
        agendaMenu.add(agendamentoMenuItem);

        horarioMedicoMenuItem.setMnemonic('s');
        horarioMedicoMenuItem.setText("Horário do Médico");
        agendaMenu.add(horarioMedicoMenuItem);

        sairMenuItem.setMnemonic('x');
        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        agendaMenu.add(sairMenuItem);

        menuBar.add(agendaMenu);

        CadastroMenu.setMnemonic('e');
        CadastroMenu.setText("Cadastro");

        pacienteMenuItem.setMnemonic('t');
        pacienteMenuItem.setText("Paciente");
        pacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteMenuItemActionPerformed(evt);
            }
        });
        CadastroMenu.add(pacienteMenuItem);

        medicoMenuItem.setMnemonic('y');
        medicoMenuItem.setText("Médico");
        CadastroMenu.add(medicoMenuItem);

        convenioMenuItem.setMnemonic('p');
        convenioMenuItem.setText("Convênio");
        CadastroMenu.add(convenioMenuItem);

        especialidadeMenuItem.setMnemonic('d');
        especialidadeMenuItem.setText("Especialidade");
        CadastroMenu.add(especialidadeMenuItem);

        estoqueMenuItem.setText("Estoque");
        CadastroMenu.add(estoqueMenuItem);
        CadastroMenu.add(cadastroSeparator);

        calendarioMenuItem.setText("Calendário");
        calendarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioMenuItemActionPerformed(evt);
            }
        });
        CadastroMenu.add(calendarioMenuItem);

        consultaCidMenuItem.setText("Consulta CID");
        CadastroMenu.add(consultaCidMenuItem);

        menuBar.add(CadastroMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Financeiro");

        grpfinanceiraMenuItem.setMnemonic('c');
        grpfinanceiraMenuItem.setText("Grupo de Despesa");
        helpMenu.add(grpfinanceiraMenuItem);

        despesaMenuItem.setMnemonic('a');
        despesaMenuItem.setText("Despesa");
        helpMenu.add(despesaMenuItem);

        grmdespesaMenuItem.setText("Gerenciamento de Despesa");
        helpMenu.add(grmdespesaMenuItem);

        ctapagarMenuItem.setText("Contas a Pagar");
        helpMenu.add(ctapagarMenuItem);

        menuBar.add(helpMenu);

        relatorioMenu.setText("Relatório");

        jMenuItem1.setText("Convênio");
        relatorioMenu.add(jMenuItem1);

        menuBar.add(relatorioMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneMdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void pacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteMenuItemActionPerformed

    private void calendarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimedMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimedMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimedMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimedMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimedMDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CadastroMenu;
    private javax.swing.JMenu agendaMenu;
    private javax.swing.JMenuItem agendamentoMenuItem;
    private javax.swing.JPopupMenu.Separator cadastroSeparator;
    private javax.swing.JMenuItem calendarioMenuItem;
    private javax.swing.JMenuItem consultaCidMenuItem;
    private javax.swing.JMenuItem convenioMenuItem;
    private javax.swing.JMenuItem ctapagarMenuItem;
    private javax.swing.JDesktopPane desktopPaneMdi;
    private javax.swing.JMenuItem despesaMenuItem;
    private javax.swing.JMenuItem especialidadeMenuItem;
    private javax.swing.JMenuItem estoqueMenuItem;
    private javax.swing.JPanel financeiroMenu;
    private javax.swing.JMenuItem grmdespesaMenuItem;
    private javax.swing.JMenuItem grpfinanceiraMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem horarioMedicoMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSplitPane jSplitPaneMdi;
    private javax.swing.JMenuItem medicoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pacienteMenuItem;
    private javax.swing.JMenu relatorioMenu;
    private javax.swing.JMenuItem sairMenuItem;
    // End of variables declaration//GEN-END:variables

}
