/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.assis.view;

/**
 *
 * @author jr
 */
public class MovimentacaoProdutoJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MovimentacaoProdutoJInternalFrame
     */
    public MovimentacaoProdutoJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMvProduto = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelMvGrupProduto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelMvProdutoUnidade = new javax.swing.JLabel();
        jTextFieldMvProdutoUnidade = new javax.swing.JTextField();
        jLabelMvProdutoSaldo = new javax.swing.JLabel();
        jTextFieldMvProdutoSaldo = new javax.swing.JTextField();
        jPanelMvProduto = new javax.swing.JPanel();
        jLabelMvMovimentacao = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabelMvQtdProduto = new javax.swing.JLabel();
        jTextFieldMvQtdProduto = new javax.swing.JTextField();
        jLabelMvVlTotal = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelMvObs = new javax.swing.JLabel();

        jLabelMvProduto.setText("Produto:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelMvGrupProduto.setText("Grupo de Produto:");

        jTextField1.setText("jTextField1");

        jLabelMvProdutoUnidade.setText("Unidade:");

        jLabelMvProdutoSaldo.setText("Saldo Atual:");

        jPanelMvProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimentação"));

        jLabelMvMovimentacao.setText("Movimentação:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelMvQtdProduto.setText("Quantidade:");

        jLabelMvVlTotal.setText("Valor Total: (Ñ unitário)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelMvObs.setText("Obs:");

        javax.swing.GroupLayout jPanelMvProdutoLayout = new javax.swing.GroupLayout(jPanelMvProduto);
        jPanelMvProduto.setLayout(jPanelMvProdutoLayout);
        jPanelMvProdutoLayout.setHorizontalGroup(
            jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMvProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMvProdutoLayout.createSequentialGroup()
                            .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelMvMovimentacao)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(122, 122, 122)
                            .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelMvQtdProduto)
                                .addComponent(jTextFieldMvQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(58, 58, 58)
                            .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelMvVlTotal)
                                .addComponent(jTextField))))
                    .addComponent(jLabelMvObs))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelMvProdutoLayout.setVerticalGroup(
            jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMvProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMvMovimentacao)
                    .addComponent(jLabelMvQtdProduto)
                    .addComponent(jLabelMvVlTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMvProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMvQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabelMvObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMvProduto)
                            .addComponent(jLabelMvGrupProduto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMvProdutoUnidade)
                                    .addComponent(jTextFieldMvProdutoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMvProdutoSaldo)
                                    .addComponent(jTextFieldMvProdutoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelMvProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMvProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabelMvGrupProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMvProdutoUnidade)
                    .addComponent(jLabelMvProdutoSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMvProdutoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMvProdutoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMvProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabelMvGrupProduto;
    private javax.swing.JLabel jLabelMvMovimentacao;
    private javax.swing.JLabel jLabelMvObs;
    private javax.swing.JLabel jLabelMvProduto;
    private javax.swing.JLabel jLabelMvProdutoSaldo;
    private javax.swing.JLabel jLabelMvProdutoUnidade;
    private javax.swing.JLabel jLabelMvQtdProduto;
    private javax.swing.JLabel jLabelMvVlTotal;
    private javax.swing.JPanel jPanelMvProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldMvProdutoSaldo;
    private javax.swing.JTextField jTextFieldMvProdutoUnidade;
    private javax.swing.JTextField jTextFieldMvQtdProduto;
    // End of variables declaration//GEN-END:variables
}
